### ISSUE TITLE
Tiles generated by kubi is not supported in marzipano viewer

### ISSUE THREAD

**Issue by jack-solutions** [indus/kubi#11]
tiles generated by kubi is not supported in marzipano viewer. the reason behind this is, z index starts from 0 in the tiling of kubi, however marzipano requires from 1.

**Comment by Arvrairobo** [comment]
yeah same, any update on that?

**Comment by Arvrairobo** [comment]
@indus

**Comment by indus** [comment]
I think the easiest solution is to fix it by using a slightly adjusted URL function in Marzipano. Something like this (this is from an old project of mine and my not work as is with newer versions of Marzipano):
``` JS
    var tileUrl = function (f, z, x, y) {
      return "tiles/" + data.id + `/dstfile_${f}/${z}/${x}/${y}.jpg`;
    };
    var source = new Marzipano.ImageUrlSource(function (tile) {
        return { url: tileUrl(tile.face, tile.z-1, tile.x, tile.y) };
    });
    var scene = viewer.createScene({
      source: source,
      geometry: geometry,
      view: view,
      pinFirstLevel: true
    });
```
Changing the output of kubi is not so easy. The dz function of VIPS that generates the tiles has no option to change the z-index.
So either kubi or the user would have to rename all the folders in some postprocessing. Because I find it a bit odd to to start an index with 1 (as Marzipano decided to do) I don't plan to change the behavior of kubi.

**Comment by jack-solutions** [comment]
yes thanks, we have sorted the problem the other ways and it is working fine.

marzipano also needs preview image in the viewer, kubi is not generating any such preview image, do you have any readymade solution for that? @indus

**Comment by jack-solutions** [comment]
i need preview image to be generated something like attached preview image, how it will work with kubi?

![preview](https://github.com/indus/kubi/assets/5101493/ddae5e90-21f7-45b0-b8f8-3b48f9139a7d)

**Comment by jack-solutions** [comment]
never mind, i have got it, thanks
