### ISSUE TITLE
Quality of tiles

### ISSUE THREAD

**Issue by jack-solutions** [indus/kubi#13]
How we can improve the image quality of tiles? right now it seems it is degrading the quality. even though we have tried 100% in Q parameter.

Let me know what am i doing wrong?

kubi -s 2048 -co tile_size=512 -co depth=onetile -co overlap=0 -co layout=google -co suffix=.jpg[Q=75] -f r l u d f b srcfile dstfile.dz

it seems tiles are generated with jpg thats why? @indus

**Comment by indus** [comment]
Because of the suffix option you are using... You can change that to any other filetype supported by Vips.Am 16.10.2023 14:39 schrieb ipangram ***@***.***>:
How we can improve the image quality of tiles? right now it seems it is degrading the quality. even though we have tried 100% in Q parameter.
Let me know what am i doing wrong?
kubi -s 2048 -co tile_size=512 -co depth=onetile -co overlap=0 -co layout=google -co suffix=.jpg[Q=75] -f r l u d f b srcfile dstfile.dz
it seems tiles are generated with jpg thats why?

**Comment by indus** [comment]
> it seems tiles are generated with jpg thats why? @indus

@jack-solutions Because of the suffix option you are using... You can change that to any other filetype supported by Vips.

try
`kubi -s 2048 -co tile_size=512 -co depth=onetile -co overlap=0 -co layout=google -co suffix=.png -f r l u d f b srcfile dstfile.dz`
or
`kubi -s 2048 -co tile_size=512 -co depth=onetile -co overlap=0 -co layout=google -co suffix=.tiff -f r l u d f b srcfile dstfile.dz`

To give you same explanation - the `dz` in in `dstfile.dz` is not a real fileype; it stands for "DeepZoom" and just says vips to create a pyramid of image tiles in a folder structure. The `layout` property is what decides how the folders/folders are organized and named. The `suffix` is what really decides on the filetype of the images with more optional parameters in `[]`. This is all Vips way of doing stuff kubi just reuses it:  https://www.libvips.org/API/current/Making-image-pyramids.html

**Comment by jack-solutions** [comment]
To give you some explanation - the dz in in dstfile.dz is not a real fileype; it stands for "DeepZoom" and just tells vips to create a pyramid of image tiles in a folder structure.
==> yes correct and we are already generating a pyramid level. thank you for the reponse on that.

let me try tiff and let you know

Thanks man
