### ISSUE TITLE
Using large files causes the software to malfunction

### ISSUE THREAD

**Issue by Ced7032** [indus/kubi#6]
The warning I got: 
GLib-GObject-WARNING **: 06:08:26.898: value "16384" of type 'gint' is invalid or out of range for property 'tile-size' of type 'gint'

The command I used:
kubi -s 16384 -co tile_size=16384 -co depth=onetile -co overlap=0 -co layout=google -co suffix=.png -f l r u d f b originalFile.png englishHasStopped.dz

My image file was 65,536 * 32,768 (2^14 * 2^13)

Using large file sizes up to this point seems to be completely fine, so does the output for smaller tiling, as a tile size of 8192 would work just fine.

Despite the bug (which is kinda ridiculous and possibly just unintended use): Massive respect for writing the only software that could handle such large files that I could find!

**Comment by indus** [comment]
That is strange, because I used vips instead of open-cv for the transform because it was able to handle images larger then 32768. So it is intended to work with files that large and larger. I will have to look into this. Am 10.12.2022 06:37 schrieb Ced7032 ***@***.***>:
The warning I got:
GLib-GObject-WARNING **: 06:08:26.898: value "16384" of type 'gint' is invalid or out of range for property 'tile-size' of type 'gint'
The command I used:
kubi -s 16384 -co tile_size=16384 -co depth=onetile -co overlap=0 -co layout=google -co suffix=.png -f l r u d f b originalFile.png englishHasStopped.dz
My image file was 65,536 * 32,768 (2^14 * 2^13)
Using large file sizes up to this point seems to be completely fine, so does the output for smaller tiling, as a tile size of 8192 would work just fine.
Despite the bug (which is kinda ridiculous and possibly just unintended use): Massive respect for writing the only software that could handle such large files that I could find!

**Comment by indus** [comment]
Just one question. What is the reason to make the tile_size the same as the size of a cube face. This sould result in only one tile for each face, right? So basically no tiling at all.Am 10.12.2022 06:37 schrieb Ced7032 ***@***.***>:
The warning I got:
GLib-GObject-WARNING **: 06:08:26.898: value "16384" of type 'gint' is invalid or out of range for property 'tile-size' of type 'gint'
The command I used:
kubi -s 16384 -co tile_size=16384 -co depth=onetile -co overlap=0 -co layout=google -co suffix=.png -f l r u d f b originalFile.png englishHasStopped.dz
My image file was 65,536 * 32,768 (2^14 * 2^13)
Using large file sizes up to this point seems to be completely fine, so does the output for smaller tiling, as a tile size of 8192 would work just fine.
Despite the bug (which is kinda ridiculous and possibly just unintended use): Massive respect for writing the only software that could handle such large files that I could find!

**Comment by indus** [comment]
It looks like the dz format of libvips only supports a max tile_size of 8192: https://github.com/libvips/libvips/blob/fa03989b6022ce2602a8fff35bae01e9e81a1a7d/doc/Making-image-pyramids.xml#L42
I had a brief look on the code there but haven't seen anything that really enforces this limit: https://github.com/libvips/libvips/blob/0629a5de7f73606c852516a420afdee4c469da9d/libvips/foreign/dzsave.c#L715. I mean `int`s allow for bigger values. But I would guess there are reasons!?

As kubi is just a thin wrapper around libvips and totally depends on it for tiling this needs to get fixed in libvips to overcome this limitation.

But in your specific case you should be able to call kubi without using the the `dz` like so:
`kubi -s 16384 -f l r u d f b originalFile.png englishHasStopped/out.png`
This should give you the 6 tiles(only the folder structure is probably different)

I'm still having a hard time to imagine why you would want tiles that large. 16k is the maximal supported texture-size for most desktop GPUs. But a lot of low-end systems often only support 4k. And I think that is the reason for tiling in the first place. Having small chunks that can be loaded by any system in short time only when needed.

**Comment by Ced7032** [comment]
Yeah being up until 6am kinda made my brain tire out. Did not read properly to know I could render without tile size.
As for my needs: I am making a map of the observable universe and need as much resolution as possible to accommodate for zooming. 64k is sadly the largest continuously rendered image of our night sky, as even this is a comparatively low resolution.

**Comment by Ced7032** [comment]
I work around the issue of GPU limitations by using tiles (which I could just take the ones generated), however to alter the image itself inside of GIMP, I like to work on one side at a time, so I would need to stitch them together only to separate them again when I'm finished. You would be surprised how well GIMP handles these images. I've had 256k squares on there and I have a 2060 mobile and some shitty laptop Ryzen CPU with 16 gigs of RAM.

**Comment by indus** [comment]
"a map of the observable universe" sounds great. Kubi was developed after (! :cry:) I've struggled with a similar task. It was not about the universe but just good old earth with 5 different 128k x 64k textures (~ 300 m resolution). I've used 1k tiles with one pixel overlap to hide the seams.

If you are in control over the render engine and care about quality I recommend having a look at the `Optimized Tangens Cubemap` https://github.com/indus/kubi#transforms
It is super easy to implement but makes quite some difference.

Good luck with your project.
